server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: es-op
  elasticsearch:
    uris: http://101.133.175.24:9200
    username:
    password:
    connection-timeout: 10s
    socket-timeout: 30s

logging:
  file:
    name: D:/Java Proj/ES-op/es/app.log
  level:
    root: INFO
    org.example: INFO
    co.elastic.clients: INFO